### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by erebe**

### CODE REVIEW

**Comment by deimosfr** [comment]
[Qovery Preview](https://www.qovery.com)
---

Qovery can create a Preview Environment for this PR.
To trigger its creation, please post a comment with one of the following command.

| Command | Blueprint environment |
|---|---|
| /qovery  preview 5ca19b4e-72e7-44bc-b758-b4a41044cc8a | [http_server - qovery-eks-tests-arm64](https://console.qovery.com/organization/460616f0-94da-4d35-b631-6fa4ed08eb9a/project/043f9fde-371a-456c-ba93-15befb7ff1b4/environment/5ca19b4e-72e7-44bc-b758-b4a41044cc8a/services/general) |
| /qovery  preview {all\|UUID1,UUID2,...} | To preview multiple environments |

---

This comment has been generated from [Qovery](https://qovery.com) AI :robot:.
Below, a word from its wisdom :
> Don’t Sacrifice Readability, you are going to debug it in 6 months

**Comment by deimosfr** [comment]
[Qovery Preview](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] http_server - qovery-eks-tests-arm64 - Update README.md - 2023-06-15T07:25:34Z](https://console.qovery.com/organization/460616f0-94da-4d35-b631-6fa4ed08eb9a/project/043f9fde-371a-456c-ba93-15befb7ff1b4/environment/1b208f50-506c-4fd8-8699-69bde46c1eb2/services/general)

 Another comment will be posted when deployments are terminated

**Comment by deimosfr** [comment]
[Qovery Preview](https://www.qovery.com)
---

A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [\[PR\] http_server - qovery-eks-tests-arm64 - Update README.md - 2023-06-15T08:03:34Z](https://console.qovery.com/organization/460616f0-94da-4d35-b631-6fa4ed08eb9a/project/043f9fde-371a-456c-ba93-15befb7ff1b4/environment/292e6fe4-910b-4e44-a5ca-1ad55be68989/services/general)

 Another comment will be posted when deployments are terminated

**Comment by deimosfr** [comment]
[Qovery Preview](https://www.qovery.com)
---

Your preview environment has been successfully deployed !
Click on the link below to open your service:
:point_right: [simple_http_server](https://75-simplehttpserver-httpserver-qovery-eks-tests-arm64.zbe9e22b0.oom.sh)
:point_right: [docker bookworm sleep](null)

**Comment by erebe** [comment]
test

**Pull request closed without merging**
