### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by erebe**

### CODE REVIEW

**Comment by mzottolaqovery** [comment]
- [ ]  test

**Comment by benjaminch** [comment]
- []  test

**Comment by benjaminch** [comment]
- [ ] test

**Comment by deimosfr** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] http_server - qovery-eks-tests-arm64 - Update README.md - 2023-05-09T15:49:19Z](https://console.qovery.com/organization/460616f0-94da-4d35-b631-6fa4ed08eb9a/project/bf620784-e81e-4f15-9b5f-cf2e6643bb7b/environment/783d6026-14c4-4469-886b-88ac0b6ea3bb/services/general)

 Another comment will be posted when deployments are terminated

**Comment by deimosfr** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] http_server - qovery-eks-tests-arm64 - Update README.md - 2023-05-11T11:29:00Z](https://console.qovery.com/organization/460616f0-94da-4d35-b631-6fa4ed08eb9a/project/bf620784-e81e-4f15-9b5f-cf2e6643bb7b/environment/67c078bc-a12a-4245-a5fb-e9058be472e6/services/general)

 Another comment will be posted when deployments are terminated

**Comment by deimosfr** [comment]
Your preview environment failed to be deployed !
Click on the link below to check the deployment logs.
:point_right: [[PR] http_server - qovery-eks-tests-arm64 - Update README.md - 2023-05-11T11:29:00Z](https://console.qovery.com/organization/460616f0-94da-4d35-b631-6fa4ed08eb9a/project/bf620784-e81e-4f15-9b5f-cf2e6643bb7b/environment/67c078bc-a12a-4245-a5fb-e9058be472e6/logs)

**Comment by deimosfr** [comment]
A preview environment was automatically created via Qovery.
Click on the link below to follow its deployment and use it.
:point_right: [[PR] http_server - qovery-eks-tests-arm64 - Update README.md - 2023-05-11T13:53:52Z](https://console.qovery.com/organization/460616f0-94da-4d35-b631-6fa4ed08eb9a/project/bf620784-e81e-4f15-9b5f-cf2e6643bb7b/environment/dc8db8b6-9dd4-4d6e-9dbc-624db36cba39/services/general)

 Another comment will be posted when deployments are terminated

**Comment by deimosfr** [comment]
Your preview environment failed to be deployed !
Click on the link below to check the deployment logs.
:point_right: [[PR] http_server - qovery-eks-tests-arm64 - Update README.md - 2023-05-11T13:53:52Z](https://console.qovery.com/organization/460616f0-94da-4d35-b631-6fa4ed08eb9a/project/bf620784-e81e-4f15-9b5f-cf2e6643bb7b/environment/dc8db8b6-9dd4-4d6e-9dbc-624db36cba39/logs)

**Pull request closed without merging**
